# Generated by Django 3.2.7 on 2021-09-20 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0002_rename_student_student1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student1',
            new_name='Student2',
        ),
    ]
