# Generated by Django 3.2.7 on 2021-09-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=20)),
                ('Phone', models.IntegerField()),
                ('Doj', models.DateField()),
                ('From', models.CharField(max_length=20)),
                ('To', models.CharField(max_length=20)),
            ],
        ),
    ]
